emeraude-erp/src/EPlan/PlanningBundle/Entity/Departement.php
<?php

namespace EPlan\PlanningBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Departement
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="EPlan\PlanningBundle\Entity\DepartementRepository")
 */
class Departement
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=120)
     */
    private $nom;
    
    /**
     * @ORM\OneToMany(targetEntity="EPlan\PlanningBundle\Entity\Mention", mappedBy="departement", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $mentions;
    
    /**
     * @ORM\OneToMany(targetEntity="EPlan\PlanningBundle\Entity\Enseignant", mappedBy="departement", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $enseignants;
    
    /**
     * @ORM\OneToMany(targetEntity="EPlan\PlanningBundle\Entity\Ec", mappedBy="departement")
     */
    private $ecs;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Departement
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    
        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->mentions = new \Doctrine\Common\Collections\ArrayCollection();
        $this->departements = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add mentions
     *
     * @param \EPlan\PlanningBundle\Entity\Mention $mentions
     * @return Departement
     */
    public function addMention(\EPlan\PlanningBundle\Entity\Mention $mentions)
    {
        $this->mentions[] = $mentions;
        $mentions ->setDepartement($this);
    
        return $this;
    }

    /**
     * Remove mentions
     *
     * @param \EPlan\PlanningBundle\Entity\Mention $mentions
     */
    public function removeMention(\EPlan\PlanningBundle\Entity\Mention $mentions)
    {
        $this->mentions->removeElement($mentions);
    }

    /**
     * Get mentions
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMentions()
    {
        return $this->mentions;
    }
    
    /**
     * Get list of all parcourtType for this department
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getParcourtTypes()
    {
        $listOfParcourtType = new \Doctrine\Common\Collections\ArrayCollection();
        foreach ($this -> mentions as $mention) {
            foreach ($mention->getParcourtTypes() as $parcourtType) {
                $listOfParcourtType[] = $parcourtType;
            }
            
        }
        return $listOfParcourtType;
    }
    
    public function getNombreDeMention() {
        return $this->mentions->count();
    }

    /**
     * Add ec
     *
     * @param \EPlan\PlanningBundle\Entity\Ec $ec
     *
     * @return Departement
     */
    public function addEc(\EPlan\PlanningBundle\Entity\Ec $ec)
    {
        $this->ecs[] = $ec;

        return $this;
    }

    /**
     * Remove ec
     *
     * @param \EPlan\PlanningBundle\Entity\Ec $ec
     */
    public function removeEc(\EPlan\PlanningBundle\Entity\Ec $ec)
    {
        $this->ecs->removeElement($ec);
    }

    /**
     * Get ecs
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEcs()
    {
        return $this->ecs;
    }

    /**
     * Add enseignant
     *
     * @param \EPlan\PlanningBundle\Entity\Enseignant $enseignant
     *
     * @return Departement
     */
    public function addEnseignant(\EPlan\PlanningBundle\Entity\Enseignant $enseignant)
    {
        $this->enseignants[] = $enseignant;
    
        return $this;
    }

    /**
     * Remove enseignant
     *
     * @param \EPlan\PlanningBundle\Entity\Enseignant $enseignant
     */
    public function removeEnseignant(\EPlan\PlanningBundle\Entity\Enseignant $enseignant)
    {
        $this->enseignants->removeElement($enseignant);
    }

    /**
     * Get enseignants
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEnseignants()
    {
        return $this->enseignants;
    }
}

emeraude-erp/src/EPlan/PlanningBundle/Entity/ParcourtType.php
<?php

namespace EPlan\PlanningBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ParcourtType
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="EPlan\PlanningBundle\Entity\ParcourtTypeRepository")
 */
class ParcourtType
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=120)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="code", type="string", length=12)
     */
    private $code;
    
    /**
     * @var 
     *
     * @ORM\ManyToOne(targetEntity="EPlan\PlanningBundle\Entity\Mention", inversedBy="parcourtTypes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $mention;
    
    /**
     * @ORM\OneToMany(targetEntity="EPlan\PlanningBundle\Entity\Etape", mappedBy="parcourtType", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $etapes;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return ParcourtType
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set code
     *
     * @param string $code
     * @return ParcourtType
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get code
     *
     * @return string 
     */
    public function getCode()
    {
        return $this->code;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->etapes = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set mention
     *
     * @param \EPlan\PlanningBundle\Entity\Mention $mention
     * @return ParcourtType
     */
    public function setMention(\EPlan\PlanningBundle\Entity\Mention $mention)
    {
        $this->mention = $mention;
    
        return $this;
    }

    /**
     * Get mention
     *
     * @return \EPlan\PlanningBundle\Entity\Mention 
     */
    public function getMention()
    {
        return $this->mention;
    }

    /**
     * Add etapes
     *
     * @param \EPlan\PlanningBundle\Entity\Etape $etapes
     * @return ParcourtType
     */
    public function addEtape(\EPlan\PlanningBundle\Entity\Etape $etapes)
    {
        $this->etapes[] = $etapes;
        $etapes ->setParcourtType($this);
    
        return $this;
    }

    /**
     * Remove etapes
     *
     * @param \EPlan\PlanningBundle\Entity\Etape $etapes
     */
    public function removeEtape(\EPlan\PlanningBundle\Entity\Etape $etapes)
    {
        $this->etapes->removeElement($etapes);
    }

    /**
     * Get etapes
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getEtapes()
    {
        return $this->etapes;
    }
    
    /**
     * Get le nombre d'étudiants du parcourt type
     *
     * @return integer 
     */
    public function getNombreEtudiants()
    {
        return 160;
    }

}

emeraude-erp/src/EPlan/PlanningBundle/Resources/views/Division/manageDivision.html.twig
{% extends "EPlanPlanningBundle::template.html.twig" %}
{% block titrePage %}Gestion{% endblock%}
{% block explicationTitrePage %}{% endblock %}
{% block pageCentrale %}
    
            <div class="col-md-3">
              <a href="compose.html" class="btn btn-primary btn-block margin-bottom">Editer</a>
              <div class="box box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title">D&eacute;partements</h3>
                  <div class="box-tools">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                  </div>
                </div>
                <div class="box-body no-padding">
                  <ul class="nav nav-pills nav-stacked">
                      {% for departement in departements %}
                          {% if loop.first %}
                              <li class="active"><a href="#"><i class="fa fa-inbox"></i> {{ departement.nom}}<span class="label label-primary pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% elseif loop.index0%5 == 1 %}
                            <li><a href="#"><i class="fa fa-envelope-o"></i> {{ departement.nom}} <span class="label label-warning pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% elseif loop.index0%5 == 2 %}
                            <li><a href="#"><i class="fa fa-file-text-o"></i> {{ departement.nom}} <span class="label label-warning pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% elseif loop.index0%5 == 3 %}
                            <li><a href="#"><i class="fa fa-filter"></i> {{ departement.nom}} <span class="label label-warning pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% elseif loop.index0%5 == 4 %}
                            <li><a href="#"><i class="fa fa-trash-o"></i> {{ departement.nom}} <span class="label label-warning pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% else %}
                            <li><a href="#"><i class="fa fa-inbox"></i> {{ departement.nom}} <span class="label label-warning pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% endif %}
                      {% endfor %}
                  </ul>
                </div><!-- /.box-body -->
              </div><!-- /. box -->
              <div class="box box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title">Menu</h3>
                  <div class="box-tools">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                  </div>
                </div>
                <div class="box-body no-padding">
                  <ul class="nav nav-pills nav-stacked">
                    <li><a href="#"><i class="fa fa-circle-o text-light-blue"></i> Reconduire les Grilles</a></li>
                    <li><a href="#"><i class="fa fa-circle-o text-light-blue"></i> Reconduire toutes les Grilles</a></li>
                  </ul>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
            <div class="col-md-9">
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Liste Des Parcourts Type</h3>
                  <div class="box-tools pull-right">
                    <div class="has-feedback">
                      <input type="text" class="form-control input-sm" placeholder="Enseignant" />
                      <span class="glyphicon glyphicon-search form-control-feedback"></span>
                    </div>
                  </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <div class="mailbox-controls">
                    <!-- Check all button -->
                    <button class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></button>
                    <div class="btn-group">
                      <button class="btn btn-default btn-sm"><i class="fa fa-trash-o"></i></button>
                      <button class="btn btn-default btn-sm"><i class="fa fa-reply"></i></button>
                      <button class="btn btn-default btn-sm"><i class="fa fa-share"></i></button>
                    </div><!-- /.btn-group -->
                    <button class="btn btn-default btn-sm"><i class="fa fa-refresh"></i></button>
                    <div class="pull-right">
                      1-50/200
                      <div class="btn-group">
                        <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
                        <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
                      </div><!-- /.btn-group -->
                    </div><!-- /.pull-right -->
                  </div>
                  <div class="table-responsive mailbox-messages">
                    <table class="table table-hover table-striped">
                      <tbody>
                          {% for mention in departements[0].mentions %}
                          {% for parcourtType in mention.parcourtTypes %}
                              <tr>
                                <td><input type="checkbox" /></td>
                                <td class="mailbox-star"><a href="#"><i class="fa fa-star text-yellow"></i></a></td>
                                <td class="mailbox-name"><a href="{{path('e_plan_planning_view_parcourt_Type', {'id': parcourtType.id})}}">{{parcourtType.code}}</a></td>
                                <td class="mailbox-subject"><b>{{ mention.nom }}</b> - {{parcourtType.nom}}</td>
                                <td class="mailbox-attachment"></td>
                                <td class="mailbox-date">{{ parcourtType.nombreEtudiants }} &eacute;tudiants</td>
                              </tr>
                          {% endfor %}    
                          {% endfor %}
                      </tbody>
                    </table><!-- /.table -->
                  </div><!-- /.mail-box-messages -->
                </div><!-- /.box-body -->
                <div class="box-footer no-padding">
                  <div class="mailbox-controls">
                    <!-- Check all button -->
                    <button class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></button>                    
                    <div class="btn-group">
                      <button class="btn btn-default btn-sm"><i class="fa fa-trash-o"></i></button>
                      <button class="btn btn-default btn-sm"><i class="fa fa-reply"></i></button>
                      <button class="btn btn-default btn-sm"><i class="fa fa-share"></i></button>
                    </div><!-- /.btn-group -->
                    <button class="btn btn-default btn-sm"><i class="fa fa-refresh"></i></button>
                    <div class="pull-right">
                      1-50/200
                      <div class="btn-group">
                        <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
                        <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
                      </div><!-- /.btn-group -->
                    </div><!-- /.pull-right -->
                  </div>
                </div>
              </div><!-- /. box -->
            </div><!-- /.col -->
{% endblock %}

emeraude-erp/src/EPlan/PlanningBundle/Resources/views/Division/menuDepartement.html.twig
 
                <div class="box box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title">D&eacute;partements</h3>
                  <div class="box-tools">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                  </div>
                </div>
                <div class="box-body no-padding">
                {% if departements is not null %}
                  <ul class="nav nav-pills nav-stacked">
                      {% for departement in departements %}
                          {% if loop.first %}
                              <li class="active"><a href="#"><i class="fa fa-inbox"></i> {{ departement.nom}}<span class="label label-primary pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% elseif loop.index0%5 == 1 %}
                            <li><a href="#"><i class="fa fa-envelope-o"></i> {{ departement.nom}} <span class="label label-warning pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% elseif loop.index0%5 == 2 %}
                            <li><a href="#"><i class="fa fa-file-text-o"></i> {{ departement.nom}} <span class="label label-warning pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% elseif loop.index0%5 == 3 %}
                            <li><a href="#"><i class="fa fa-filter"></i> {{ departement.nom}} <span class="label label-warning pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% elseif loop.index0%5 == 4 %}
                            <li><a href="#"><i class="fa fa-trash-o"></i> {{ departement.nom}} <span class="label label-warning pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% else %}
                            <li><a href="#"><i class="fa fa-inbox"></i> {{ departement.nom}} <span class="label label-warning pull-right">{{ departement.nombreDeMention }}</span></a></li>
                          {% endif %}
                      {% endfor %}
                  </ul>
                  {% else %}
                  {% endif%}
                </div><!-- /.box-body -->
              </div><!-- /. box -->
            